version: '3.7'

services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root

  dbmate:
    build: ./dbmate
    depends_on:
      - mariadb
    volumes:
      - ./db/:/db/
    entrypoint:
    - /bin/sh
    - -c
    - 'echo "You need to docker exec in this container now ..."; sleep 3h'
